### PR TITLE
Check if ped in the town where the bank is

### PR DESCRIPTION
**Pull request by xrb936**
In case server owner set all bank names the same, such as "Bank"

### CODE REVIEW

**Comment by outsider31000** [comment]
if my bank is called something else than any of those city names will it still work?

**Comment by xrb936** [comment]
It checks the index, not the name. As long as the index is a valid town hash, it works.

**Comment by outsider31000** [comment]
the index of what ?

**Comment by outsider31000** [comment]
ah based on the coords.

**Comment by xrb936** [comment]
And the index of the bank in config

Config.banks = {
    Valentine = {
        name = "Bank"
......

**Pull request merged**
