### PR TITLE
v1.5 Improving Vorp Banking

### PR DESCRIPTION
**Pull request by cl3i550n**
v1.5
- Improving translation.
- changed exports.oxmysql:execute to MySQL.
- fix(client) close menu after deposit or withdraw, fix dump money after player disconnect ethernet.
- Add dependency oxmysql in fxmanifest.

### CODE REVIEW

**Comment by outsider31000** [comment]
its doing the same thing. i cannot see what you are modifying.

**Comment by cl3i550n** [comment]
> its doing the same thing. i cannot see what you are modifying.

after your check... i go to put server and client inside folder, ok? Git is acuse this file was deleted, but only moved to inside folder.

**Comment by cl3i550n** [comment]
Your check?

**Comment by outsider31000** [comment]
image
this was removed 
image
this was added 

where is the new event being registered ?

**Comment by cl3i550n** [comment]
> image
> this was removed 
> image
> this was added 
> 
> where is the new event being registered ?

Yes!  The event already existed on the client, so I replaced it.  The reason is that as the menu is closed after depositing or withdrawing.

**Pull request merged**
