### PR TITLE
Language system

### PR DESCRIPTION
**Pull request by r3ps4J**
Hi there, I have added a language system to make it easier to add new languages and switch between languages. Switching can be done with the new config option Config.languageCode. This way you won't have config files for each language which need to be updated everytime a new config option gets added.

I also added a missing translation to the German file and added a Dutch translation as well.

### CODE REVIEW

**Comment by outsider31000** [comment]
did you test this ?

**Comment by outsider31000** [comment]
ywhy remove the folder in the fxmanifest ?
image

another error was you changed version in the fxmanifest without changing the version file. but that's up to the VORP team to add versions to it not users.
make your pr leave the versions to us.

test what you just share and you will see

**Comment by r3ps4J** [comment]
I did test this and everyting worked for me like it should, bumped version afterwards since I saw someone else do it as well. I don't understand what you mean by removing the folder, I only added the languages folder to the manifest. I'll remove the version bump.

**Comment by outsider31000** [comment]
ahah my bad i thought you removed lol i was seeing it backwards  yeah just remove the version please and thanks

**Pull request merged**
